--
-- PostgreSQL database dump
--

-- Dumped from database version 14.8 (Homebrew)
-- Dumped by pg_dump version 14.8 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: main_app_city; Type: TABLE; Schema: public; Owner: jialingye
--

CREATE TABLE public.main_app_city (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    population integer NOT NULL,
    country_id bigint NOT NULL
);


ALTER TABLE public.main_app_city OWNER TO jialingye;

--
-- Name: main_app_city_id_seq; Type: SEQUENCE; Schema: public; Owner: jialingye
--

ALTER TABLE public.main_app_city ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_app_city_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: main_app_city; Type: TABLE DATA; Schema: public; Owner: jialingye
--

INSERT INTO main_app_city VALUES (2, 'Paris', 2100000, 5);
INSERT INTO main_app_city VALUES (3, 'Chicago', 2746000, 7);
INSERT INTO main_app_city VALUES (4, 'New York', 8800000, 7);
INSERT INTO main_app_city VALUES (5, 'San Francisco', 808437, 7);
INSERT INTO main_app_city VALUES (6, 'Los Angeles', 3900000, 7);
INSERT INTO main_app_city VALUES (7, 'Boston', 676647, 7);
INSERT INTO main_app_city VALUES (8, 'Miami', 442241, 7);
INSERT INTO main_app_city VALUES (9, 'Seattle', 749256, 7);
INSERT INTO main_app_city VALUES (10, 'Rome', 2860000, 3);
INSERT INTO main_app_city VALUES (11, 'Colmar', 40000, 5);
INSERT INTO main_app_city VALUES (12, 'Florence', 234234, 3);
INSERT INTO main_app_city VALUES (13, 'Venice', 94523, 3);
INSERT INTO main_app_city VALUES (14, 'Sydney', 500340, 2);
INSERT INTO main_app_city VALUES (15, 'Brisbane', 1242093, 2);
INSERT INTO main_app_city VALUES (16, 'Golden Coast', 234235, 2);
INSERT INTO main_app_city VALUES (17, 'Cairns', 153952, 2);
INSERT INTO main_app_city VALUES (18, 'Athen', 564034, 12);
INSERT INTO main_app_city VALUES (19, 'Oia', 24053, 12);
INSERT INTO main_app_city VALUES (20, 'Bangkok', 3440001, 6);
INSERT INTO main_app_city VALUES (21, 'Phuket', 416582, 6);
INSERT INTO main_app_city VALUES (22, 'Cancun', 350465, 9);
INSERT INTO main_app_city VALUES (23, 'Toronto', 4324302, 8);
INSERT INTO main_app_city VALUES (24, 'Hong Kong', 7000000, 11);
INSERT INTO main_app_city VALUES (25, 'Milan', 54324, 3);
INSERT INTO main_app_city VALUES (26, 'Cinque Terre', 25304, 3);
INSERT INTO main_app_city VALUES (27, 'Vatican', 4435, 3);
INSERT INTO main_app_city VALUES (28, 'Tokyo', 13960000, 1);
INSERT INTO main_app_city VALUES (29, 'Osaka', 2691000, 1);
INSERT INTO main_app_city VALUES (30, 'Kyoto', 1475000, 1);
INSERT INTO main_app_city VALUES (31, 'Nara', 360310, 1);
INSERT INTO main_app_city VALUES (32, 'Sapporo', 1952000, 1);
INSERT INTO main_app_city VALUES (33, 'Otaru', 324800, 1);
INSERT INTO main_app_city VALUES (34, 'Furano', 22715, 1);
INSERT INTO main_app_city VALUES (35, 'Orlando', 1502512, 7);
INSERT INTO main_app_city VALUES (36, 'Lucerne', 81592, 4);
INSERT INTO main_app_city VALUES (37, 'Zurich', 402762, 4);
INSERT INTO main_app_city VALUES (38, 'Interlaken', 5346, 4);
INSERT INTO main_app_city VALUES (39, 'Thun', 42623, 4);
INSERT INTO main_app_city VALUES (40, 'Lungern', 2049, 4);
INSERT INTO main_app_city VALUES (41, 'Grindelwald', 3826, 4);
INSERT INTO main_app_city VALUES (42, 'Lauterbrunnen', 3501, 4);


--
-- Name: main_app_city_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jialingye
--

SELECT pg_catalog.setval('public.main_app_city_id_seq', 42, true);


--
-- Name: main_app_city main_app_city_pkey; Type: CONSTRAINT; Schema: public; Owner: jialingye
--

ALTER TABLE ONLY public.main_app_city
    ADD CONSTRAINT main_app_city_pkey PRIMARY KEY (id);


--
-- Name: main_app_city_country_id_fb06f48e; Type: INDEX; Schema: public; Owner: jialingye
--

CREATE INDEX main_app_city_country_id_fb06f48e ON public.main_app_city USING btree (country_id);


--
-- Name: main_app_city main_app_city_country_id_fb06f48e_fk_main_app_country_id; Type: FK CONSTRAINT; Schema: public; Owner: jialingye
--

ALTER TABLE ONLY public.main_app_city
    ADD CONSTRAINT main_app_city_country_id_fb06f48e_fk_main_app_country_id FOREIGN KEY (country_id) REFERENCES public.main_app_country(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

