--
-- PostgreSQL database dump
--

-- Dumped from database version 14.8 (Homebrew)
-- Dumped by pg_dump version 14.8 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: main_app_country; Type: TABLE; Schema: public; Owner: jialingye
--

CREATE TABLE public.main_app_country (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    img character varying(250) NOT NULL,
    bio text NOT NULL,
    travel_again boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.main_app_country OWNER TO jialingye;

--
-- Name: main_app_country_id_seq; Type: SEQUENCE; Schema: public; Owner: jialingye
--

ALTER TABLE public.main_app_country ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_app_country_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: main_app_country; Type: TABLE DATA; Schema: public; Owner: jialingye
--

INSERT INTO main_app_country VALUES (2, 'Austrilia', 'https://estatic.universityguru.com/images/cities/new/c94_1.jpg', 'Australia is the largest country by area in Oceania and the world''s sixth-largest country. Australia is the oldest, flattest, and driest inhabited continent, ...', false, '2023-06-26 10:37:38.107519-05');
INSERT INTO main_app_country VALUES (3, 'Italy', 'https://www.state.gov/wp-content/uploads/2018/11/Italy-2109x1406.jpg', 'Italy was the native place of civilizations such as the Italic peoples and the Etruscans, while due to its central geographic location in Southern Europe and the Mediterranean, the country has also historically been home to myriad peoples and cultures, who immigrated to the peninsula throughout history', false, '2023-06-26 10:39:29.339966-05');
INSERT INTO main_app_country VALUES (4, 'Switzerland', 'https://media.istockphoto.com/id/945092130/photo/thun-cityspace-with-alps-mountain-and-lake-in-switzerland.webp?s=2048x2048&w=is&k=20&c=hAhT2Yfc_x3NQiAicn0qqE8g1LCMSY-rgc5gwiQ_NnU=', 'Switzerland, officially the Swiss Confederation, is a landlocked country located at the confluence of Western, Central and Southern Europe. It is bordered by Italy to the south, France to the west, Germany to the north and Austria and Liechtenstein to the east.', true, '2023-06-26 10:41:31.963894-05');
INSERT INTO main_app_country VALUES (5, 'France', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg/1200px-La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg', 'France (French: [fʁɑ̃s] Listen), officially the French Republic (French: République française [ʁepyblik fʁɑ̃sɛz]),[14] is a country located primarily in Western Europe. It also includes overseas regions and territories in the Americas and the Atlantic, Pacific and Indian Oceans,[XII] giving it one of the largest discontiguous exclusive economic zones in the world. Its metropolitan area extends from the Rhine to the Atlantic Ocean and from the Mediterranean Sea to the English Channel and the Nort', true, '2023-06-26 10:42:35.657675-05');
INSERT INTO main_app_country VALUES (7, 'United States', 'https://www.nationsonline.org/gallery/USA/Mount-Rushmore.jpg', 'home country', true, '2023-06-26 10:45:33.72035-05');
INSERT INTO main_app_country VALUES (9, 'Mexico', 'https://comercial-production-gx-cms-content-bucket.s3.amazonaws.com/concentrador-hoteles/destino/mobile/cancun.jpg', 'nice place', true, '2023-06-26 10:47:30.244335-05');
INSERT INTO main_app_country VALUES (10, 'Taiwan', 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-760w,f_auto,q_auto:best/rockcms/2023-06/230621-taipei-skyline-mb-1054-aa6743.jpg', 'Taiwan,[II][m] officially the Republic of China (ROC),[I][n] is a country[32] in East Asia. It is located at the junction of the East and South China Seas in the northwestern Pacific Ocean, with the People''s Republic of China (PRC) to the northwest, Japan to the northeast, and the Philippines to the south.', false, '2023-06-26 11:43:16.043141-05');
INSERT INTO main_app_country VALUES (1, 'Japan', 'https://www.travelandleisure.com/thmb/XNm_s_lwnBKzsFv-q6MqpZ7ptFk=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/sakura-temple-pagoda-japan-VISITJP0218-73f37dad55eb4cb5b02ea4ae0eee714d.jpg', 'East Asia Country', true, '2023-06-26 10:34:28.459305-05');
INSERT INTO main_app_country VALUES (11, 'Hong Kong', 'https://www.nationsonline.org/gallery/Hong-Kong/Hong-Kong-skyline-at-night.jpg', 'Dying City', true, '2023-06-29 09:50:17.220213-05');
INSERT INTO main_app_country VALUES (6, 'Thailand', 'https://c4.wallpaperflare.com/wallpaper/568/391/699/palaces-grand-palace-bangkok-thailand-wallpaper-preview.jpg', 'Thailand officially the Kingdom of Thailand and historically known as Siam is a country in Southeast Asia on the Indochinese Peninsula. With a population of almost 70 million,[12] it spans 513,120 square kilometres (198,120 sq mi). Thailand is bordered to the north by Myanmar and Laos, to the east by Laos and Cambodia, to the south by the Gulf of Thailand and Malaysia, and to the west by the Andaman Sea; it also shares mar', true, '2023-06-26 10:44:19.979556-05');
INSERT INTO main_app_country VALUES (8, 'Canada', 'https://mcdn.wallpapersafari.com/medium/22/22/QuN46y.jpg', 'Too cold', true, '2023-06-26 10:46:32.105769-05');
INSERT INTO main_app_country VALUES (12, 'Greece', 'https://s27363.pcdn.co/wp-content/uploads/2020/05/10-Day-Greece-Itinerary.jpg.optimal.jpg', 'Been there in 2012', false, '2023-06-29 09:56:09.47566-05');


--
-- Name: main_app_country_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jialingye
--

SELECT pg_catalog.setval('public.main_app_country_id_seq', 12, true);


--
-- Name: main_app_country main_app_country_pkey; Type: CONSTRAINT; Schema: public; Owner: jialingye
--

ALTER TABLE ONLY public.main_app_country
    ADD CONSTRAINT main_app_country_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

